### ISSUE TITLE
Failed, went wrong at DensifyPointCloud - How to Troubleshoot?

### ISSUE THREAD

**Issue by michacassola** [edin45/simple_photogrammetry_gui#3]
Hey, thanks for this software. I get the error "Failed, went wrong at DensifyPointCloud".
How do I troubleshoot?

I guess it could be because the cheap cameras RAW files have a black border around them?
I will try with lens correction turned on in darktable.

I am referring to your video: https://www.youtube.com/watch?v=3EqHA10EYfE

I am using the latest Windows 11 and went through the installation steps outlined in the YT-video.

**Comment by edin45** [comment]
Hey there, What file format do you use? The application does only support 8-bit images, and was only tested with png and jpg, so RAW images aren't supported - Let me know if that helps!

**Comment by michacassola** [comment]
I went through the video and of course exported 8-bit PNGs.
According to your manual overview it immediately jumps to step 7, it spends less than 2 seconds on the steps before that.
To troubleshoot I fed the images to COLMAPs GUI -> automatic reconstruction and it is still calculating now and generating stuff... So it seems to be you not me. :D :D

**Comment by edin45** [comment]
Ok, you're right then it's probably an issue with the application, could you send me the temp folder that the application generated in the output folder? That would help me figure out what's going on.

**Comment by michacassola** [comment]
Attached the folder.
Going through it, it seems COLMAP never even ran.
[temp.zip](https://github.com/edin45/simple_photogrammetry_gui/files/11136892/temp.zip)

**Comment by edin45** [comment]
Ahh I know what the issue is, Some of your file paths have a space in them, that is the issue, just remove the space, and It should work. Let me know if that works.

**Comment by michacassola** [comment]
It works, thanks!
Please include in your instructions, or better yet, you might want to accept spaces in the app?

**Comment by edin45** [comment]
Glad it works! I'll add a warning to the app, because I already tried allowing spaces & It didn't work at all.
